CREATE DATABASE IF NOT EXISTS take_one;
USE take_one;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(100) DEFAULT NULL,
  college VARCHAR(150) DEFAULT NULL,
  city VARCHAR(120) DEFAULT NULL,
  bio TEXT DEFAULT NULL,
  skills TEXT DEFAULT NULL,
  portfolio VARCHAR(255) DEFAULT NULL,
  avatar_url VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
);

CREATE TABLE IF NOT EXISTS scripts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED DEFAULT NULL,
  title VARCHAR(180) NOT NULL,
  genre VARCHAR(80) DEFAULT NULL,
  synopsis TEXT DEFAULT NULL,
  poster_url VARCHAR(255) DEFAULT NULL,
  roles_needed VARCHAR(255) DEFAULT NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'Open for collaboration',
  media_links TEXT DEFAULT NULL,
  role_data TEXT DEFAULT NULL,
  work_type VARCHAR(50) NOT NULL DEFAULT 'Script',
  approval_status VARCHAR(50) NOT NULL DEFAULT 'pending',
  approved_by INT UNSIGNED DEFAULT NULL,
  approved_at TIMESTAMP NULL DEFAULT NULL,
  moderation_notes TEXT DEFAULT NULL,
  payment_status VARCHAR(50) NOT NULL DEFAULT 'pending',
  payment_id VARCHAR(255) DEFAULT NULL,
  payment_verified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_scripts_user_id (user_id),
  KEY idx_scripts_genre (genre),
  CONSTRAINT fk_scripts_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

ALTER TABLE scripts ADD COLUMN IF NOT EXISTS media_links TEXT DEFAULT NULL;
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS role_data TEXT DEFAULT NULL;
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS work_type VARCHAR(50) NOT NULL DEFAULT 'Script';
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS approval_status VARCHAR(50) NOT NULL DEFAULT 'pending';
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS approved_by INT UNSIGNED DEFAULT NULL;
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS moderation_notes TEXT DEFAULT NULL;
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) NOT NULL DEFAULT 'pending';
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS payment_id VARCHAR(255) DEFAULT NULL;
ALTER TABLE scripts ADD COLUMN IF NOT EXISTS payment_verified BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS collaboration_requests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  script_id INT UNSIGNED NOT NULL,
  requester_id INT UNSIGNED NOT NULL,
  owner_id INT UNSIGNED NOT NULL,
  message TEXT DEFAULT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_script_requester (script_id, requester_id),
  KEY idx_requests_owner_id (owner_id),
  KEY idx_requests_requester_id (requester_id),
  CONSTRAINT fk_requests_script
    FOREIGN KEY (script_id)
    REFERENCES scripts(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_requests_requester
    FOREIGN KEY (requester_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_requests_owner
    FOREIGN KEY (owner_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS script_drafts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED DEFAULT NULL,
  title VARCHAR(180) NOT NULL,
  genre VARCHAR(80) DEFAULT NULL,
  synopsis TEXT DEFAULT NULL,
  poster_url VARCHAR(255) DEFAULT NULL,
  roles_needed VARCHAR(255) DEFAULT NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'Open for collaboration',
  media_links TEXT DEFAULT NULL,
  role_data TEXT DEFAULT NULL,
  work_type VARCHAR(50) NOT NULL DEFAULT 'Script',
  temp_path VARCHAR(255) DEFAULT NULL,
  metadata JSON DEFAULT NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_drafts_user_id (user_id),
  CONSTRAINT fk_drafts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

ALTER TABLE script_drafts ADD COLUMN IF NOT EXISTS temp_path VARCHAR(255) DEFAULT NULL;
ALTER TABLE script_drafts ADD COLUMN IF NOT EXISTS metadata JSON DEFAULT NULL;
ALTER TABLE script_drafts ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP NULL DEFAULT NULL;

CREATE TABLE IF NOT EXISTS script_upload_payments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  draft_id INT UNSIGNED DEFAULT NULL,
  script_id INT UNSIGNED DEFAULT NULL,
  razorpay_order_id VARCHAR(255) NOT NULL,
  razorpay_payment_id VARCHAR(255) DEFAULT NULL,
  razorpay_signature VARCHAR(255) DEFAULT NULL,
  amount DECIMAL(10, 2) NOT NULL DEFAULT 49.00,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_payments_order_id (razorpay_order_id),
  KEY idx_payments_user_id (user_id),
  KEY idx_payments_draft_id (draft_id),
  CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_payments_draft FOREIGN KEY (draft_id) REFERENCES script_drafts(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS moderation_logs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  moderator_id INT UNSIGNED DEFAULT NULL,
  action VARCHAR(100) NOT NULL,
  script_id INT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_moderation_logs_moderator_id (moderator_id),
  KEY idx_moderation_logs_script_id (script_id),
  CONSTRAINT fk_moderation_logs_moderator FOREIGN KEY (moderator_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS tasks (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  conversation_id INT UNSIGNED DEFAULT NULL,
  creator_id INT UNSIGNED DEFAULT NULL,
  assignee_id INT UNSIGNED DEFAULT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  credits INT UNSIGNED NOT NULL DEFAULT 0,
  category VARCHAR(100) NOT NULL DEFAULT 'general',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending',
  priority VARCHAR(50) NOT NULL DEFAULT 'Medium',
  due_date TIMESTAMP NULL DEFAULT NULL,
  reward_credits INT UNSIGNED NOT NULL DEFAULT 0,
  approval_status VARCHAR(50) NOT NULL DEFAULT 'Pending',
  completed_at TIMESTAMP NULL DEFAULT NULL,
  approved_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tasks_conversation_id (conversation_id),
  KEY idx_tasks_active (active),
  KEY idx_tasks_category (category)
);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS credits INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS category VARCHAR(100) NOT NULL DEFAULT 'general';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tasks MODIFY COLUMN conversation_id INT UNSIGNED DEFAULT NULL;
ALTER TABLE tasks MODIFY COLUMN creator_id INT UNSIGNED DEFAULT NULL;

CREATE TABLE IF NOT EXISTS task_submissions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  credits_awarded INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_task_submission_user (task_id, user_id),
  KEY idx_task_submissions_user_id (user_id),
  KEY idx_task_submissions_status (status),
  CONSTRAINT fk_task_submissions_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_task_submissions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
