name: GSSoC Auto Approval Label

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  add-gssoc-label:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Add gssoc:approved label if GSSoC mentioned
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;

            const content = `
              ${pr.title}
              ${pr.body || ""}
            `.toLowerCase();

            if (
              content.includes("gssoc") ||
              content.includes("gssoc'26") ||
              content.includes("gssoc 2026")
            ) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ["gssoc:approved"]
              });

              console.log("gssoc:approved label added");
            } else {
              console.log("No GSSoC mention found");
            }
